title: Inyoung Oh
description: 연구 · 프로젝트 · 글 아카이브
url: "https://inyoungoh-cde.github.io"
baseurl: ""
timezone: Asia/Seoul

# ★ 테마 교체
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# 상단 메뉴 (원하면 유지/수정)
collections:
  publications:
    output: true
    permalink: /publications/:path/


# 사이드바·프로필 기본값
author:
  name: "Inyoung Oh"
  avatar: "/assets/images/profile.jpg"   # 3단계에서 이미지 추가
  bio: "HCI / AI & ST-OSCs / 3D Vision"
  location: "GIST, Republic of Korea"
  links:
    - label: "Email"
      url: "mailto:your_email@example.com"
      icon: "fas fa-envelope"
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=XXXX"
      icon: "ai ai-google-scholar"
    - label: "GitHub"
      url: "https://github.com/inyoungoh-cde"
      icon: "fab fa-github"
    - label: "Curriculum Vitae"
      url: "/assets/CV.pdf"
      icon: "far fa-file-pdf"

# 내비게이션 (원하면 수정)
#nav:
#  - title: "about"
#    url: /about/
#  - title: "publication"
#    url: /publications/
