title: Inyoung Oh
description: 연구 · 프로젝트 · 글 아카이브
url: "https://inyoungoh-cde.github.io"
baseurl: ""
timezone: Asia/Seoul

# ★ 테마 교체
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# 상단 메뉴 (원하면 유지/수정)
collections:
  publications:
    output: true
    permalink: /publications/:path/


# 사이드바·프로필 기본값
author:
  name: "Inyoung Oh"
  avatar: "/assets/images/profile.jpg"
  bio: "CAD/CAM / 2D/3D Vision / Spatial Intelligence"
  location: "GIST, Republic of Korea"
  links:
    - label: "Email"
      url: "mailto:iyohcde@gmail.com"
      icon: "fas fa-envelope"
    - label: "Google Scholar"
      url: "https://scholar.google.co.kr/citations?hl=ko&user=e3h5YtAAAAAJ&view_op=list_works&sortby=pubdate"
      icon: "fas fa-graduation-cap"   # <- 안 보이면 'fas fa-graduation-cap'로  ai ai-google-scholar
    - label: "GitHub"
      url: "https://github.com/inyoungoh-cde"
      icon: "fab fa-github"
    - label: "Curriculum Vitae"
      url: "/assets/CV.pdf"
      icon: "far fa-file-pdf"

# 내비게이션 (원하면 수정)
#nav:
#  - title: "about"
#    url: /about/
#  - title: "publication"
#    url: /publications/
